# ray tune example
loss:
  Ackley:
    x1: [1., 1.]
    steps: 100
  Absolute:
    x1: 3.
    steps: 50
  Sinusoidal:
    x1: 1.
    steps: 50
optimizer:
  SGD:
    lr: [.001, .01, .1]
    momentum: [.1, .9]
  Adam:
    lr: [.0001, .01, .1]
    eps: [1.e-8, 1.e-9]
  Cocob:
    alpha: [1, 10, 100]