# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# ...
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    env:
      USING_COVERAGE: "3.8"

    steps:
      - name: Check-out the repo under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: $

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black coverage flake8 flit mccabe mypy pylint pytest tox tox-gh-actions

      - name: Run tox
        run: |
          python -m tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: contains(env.USING_COVERAGE, matrix.python-version)
        with:
          fail_ci_if_error: true
